#!/bin/bash
#
#
#
# Traces:
#    cassandra_phase0_4T
#    cassandra_phase1_4T
#    cassandra_phase2_4T
#    cassandra_phase3_4T
#    cassandra_phase4_4T
#    cassandra_phase5_4T
#
#
# Experiments:
#    nopref: --warmup_instructions=50000000 --simulation_instructions=150000000 --config=$(PYTHIA_HOME)/config/nopref.ini --dram_io_freq=2400
#    spp: --warmup_instructions=50000000 --simulation_instructions=150000000 --l2c_prefetcher_types=spp_dev2 --config=$(PYTHIA_HOME)/config/spp_dev2.ini --dram_io_freq=2400
#    bingo: --warmup_instructions=50000000 --simulation_instructions=150000000 --l2c_prefetcher_types=bingo --config=$(PYTHIA_HOME)/config/bingo.ini --dram_io_freq=2400
#    mlop: --warmup_instructions=50000000 --simulation_instructions=150000000 --l2c_prefetcher_types=mlop --config=$(PYTHIA_HOME)/config/mlop.ini --dram_io_freq=2400
#    pythia: --warmup_instructions=50000000 --simulation_instructions=150000000 --l2c_prefetcher_types=scooby --config=$(PYTHIA_HOME)/config/pythia.ini --dram_io_freq=2400
#    imp_pythia: --warmup_instructions=50000000 --simulation_instructions=150000000 --l2c_prefetcher_types=scooby --config=$(PYTHIA_HOME)/config/pythia_mod.ini --dram_io_freq=2400
#    dspatch: --warmup_instructions=50000000 --simulation_instructions=150000000 --l2c_prefetcher_types=dspatch --config=$(PYTHIA_HOME)/config/dspatch.ini --dram_io_freq=2400
#    ppf: --warmup_instructions=50000000 --simulation_instructions=150000000 --l2c_prefetcher_types=spp_ppf_dev --config=$(PYTHIA_HOME)/config/spp_ppf_dev.ini --dram_io_freq=2400
#
#
#
#
/data3/bin/perceptron-multi-multi-no-ship-4core --warmup_instructions=50000000 --simulation_instructions=150000000 --config=/data3/config/nopref.ini --dram_io_freq=2400 --knob_cloudsuite=true -traces /data3/CASSANDRA/traces/cassandra_phase0_core0.trace.xz /data3/CASSANDRA/traces/cassandra_phase0_core1.trace.xz /data3/CASSANDRA/traces/cassandra_phase0_core2.trace.xz /data3/CASSANDRA/traces/cassandra_phase0_core3.trace.xz > cassandra_phase0_4T_nopref.out 2>&1
/data3/bin/perceptron-multi-multi-no-ship-4core --warmup_instructions=50000000 --simulation_instructions=150000000 --l2c_prefetcher_types=spp_dev2 --config=/data3/config/spp_dev2.ini --dram_io_freq=2400 --knob_cloudsuite=true -traces /data3/CASSANDRA/traces/cassandra_phase0_core0.trace.xz /data3/CASSANDRA/traces/cassandra_phase0_core1.trace.xz /data3/CASSANDRA/traces/cassandra_phase0_core2.trace.xz /data3/CASSANDRA/traces/cassandra_phase0_core3.trace.xz > cassandra_phase0_4T_spp.out 2>&1
/data3/bin/perceptron-multi-multi-no-ship-4core --warmup_instructions=50000000 --simulation_instructions=150000000 --l2c_prefetcher_types=bingo --config=/data3/config/bingo.ini --dram_io_freq=2400 --knob_cloudsuite=true -traces /data3/CASSANDRA/traces/cassandra_phase0_core0.trace.xz /data3/CASSANDRA/traces/cassandra_phase0_core1.trace.xz /data3/CASSANDRA/traces/cassandra_phase0_core2.trace.xz /data3/CASSANDRA/traces/cassandra_phase0_core3.trace.xz > cassandra_phase0_4T_bingo.out 2>&1
/data3/bin/perceptron-multi-multi-no-ship-4core --warmup_instructions=50000000 --simulation_instructions=150000000 --l2c_prefetcher_types=mlop --config=/data3/config/mlop.ini --dram_io_freq=2400 --knob_cloudsuite=true -traces /data3/CASSANDRA/traces/cassandra_phase0_core0.trace.xz /data3/CASSANDRA/traces/cassandra_phase0_core1.trace.xz /data3/CASSANDRA/traces/cassandra_phase0_core2.trace.xz /data3/CASSANDRA/traces/cassandra_phase0_core3.trace.xz > cassandra_phase0_4T_mlop.out 2>&1
/data3/bin/perceptron-multi-multi-no-ship-4core --warmup_instructions=50000000 --simulation_instructions=150000000 --l2c_prefetcher_types=scooby --config=/data3/config/pythia.ini --dram_io_freq=2400 --knob_cloudsuite=true -traces /data3/CASSANDRA/traces/cassandra_phase0_core0.trace.xz /data3/CASSANDRA/traces/cassandra_phase0_core1.trace.xz /data3/CASSANDRA/traces/cassandra_phase0_core2.trace.xz /data3/CASSANDRA/traces/cassandra_phase0_core3.trace.xz > cassandra_phase0_4T_pythia.out 2>&1
/data3/bin/perceptron-multi-multi-no-ship-4core --warmup_instructions=50000000 --simulation_instructions=150000000 --l2c_prefetcher_types=scooby --config=/data3/config/pythia_mod.ini --dram_io_freq=2400 --knob_cloudsuite=true -traces /data3/CASSANDRA/traces/cassandra_phase0_core0.trace.xz /data3/CASSANDRA/traces/cassandra_phase0_core1.trace.xz /data3/CASSANDRA/traces/cassandra_phase0_core2.trace.xz /data3/CASSANDRA/traces/cassandra_phase0_core3.trace.xz > cassandra_phase0_4T_imp_pythia.out 2>&1
/data3/bin/perceptron-multi-multi-no-ship-4core --warmup_instructions=50000000 --simulation_instructions=150000000 --l2c_prefetcher_types=dspatch --config=/data3/config/dspatch.ini --dram_io_freq=2400 --knob_cloudsuite=true -traces /data3/CASSANDRA/traces/cassandra_phase0_core0.trace.xz /data3/CASSANDRA/traces/cassandra_phase0_core1.trace.xz /data3/CASSANDRA/traces/cassandra_phase0_core2.trace.xz /data3/CASSANDRA/traces/cassandra_phase0_core3.trace.xz > cassandra_phase0_4T_dspatch.out 2>&1
/data3/bin/perceptron-multi-multi-no-ship-4core --warmup_instructions=50000000 --simulation_instructions=150000000 --l2c_prefetcher_types=spp_ppf_dev --config=/data3/config/spp_ppf_dev.ini --dram_io_freq=2400 --knob_cloudsuite=true -traces /data3/CASSANDRA/traces/cassandra_phase0_core0.trace.xz /data3/CASSANDRA/traces/cassandra_phase0_core1.trace.xz /data3/CASSANDRA/traces/cassandra_phase0_core2.trace.xz /data3/CASSANDRA/traces/cassandra_phase0_core3.trace.xz > cassandra_phase0_4T_ppf.out 2>&1
/data3/bin/perceptron-multi-multi-no-ship-4core --warmup_instructions=50000000 --simulation_instructions=150000000 --config=/data3/config/nopref.ini --dram_io_freq=2400 --knob_cloudsuite=true -traces /data3/CASSANDRA/traces/cassandra_phase1_core0.trace.xz /data3/CASSANDRA/traces/cassandra_phase1_core1.trace.xz /data3/CASSANDRA/traces/cassandra_phase1_core2.trace.xz /data3/CASSANDRA/traces/cassandra_phase1_core3.trace.xz > cassandra_phase1_4T_nopref.out 2>&1
/data3/bin/perceptron-multi-multi-no-ship-4core --warmup_instructions=50000000 --simulation_instructions=150000000 --l2c_prefetcher_types=spp_dev2 --config=/data3/config/spp_dev2.ini --dram_io_freq=2400 --knob_cloudsuite=true -traces /data3/CASSANDRA/traces/cassandra_phase1_core0.trace.xz /data3/CASSANDRA/traces/cassandra_phase1_core1.trace.xz /data3/CASSANDRA/traces/cassandra_phase1_core2.trace.xz /data3/CASSANDRA/traces/cassandra_phase1_core3.trace.xz > cassandra_phase1_4T_spp.out 2>&1
/data3/bin/perceptron-multi-multi-no-ship-4core --warmup_instructions=50000000 --simulation_instructions=150000000 --l2c_prefetcher_types=bingo --config=/data3/config/bingo.ini --dram_io_freq=2400 --knob_cloudsuite=true -traces /data3/CASSANDRA/traces/cassandra_phase1_core0.trace.xz /data3/CASSANDRA/traces/cassandra_phase1_core1.trace.xz /data3/CASSANDRA/traces/cassandra_phase1_core2.trace.xz /data3/CASSANDRA/traces/cassandra_phase1_core3.trace.xz > cassandra_phase1_4T_bingo.out 2>&1
/data3/bin/perceptron-multi-multi-no-ship-4core --warmup_instructions=50000000 --simulation_instructions=150000000 --l2c_prefetcher_types=mlop --config=/data3/config/mlop.ini --dram_io_freq=2400 --knob_cloudsuite=true -traces /data3/CASSANDRA/traces/cassandra_phase1_core0.trace.xz /data3/CASSANDRA/traces/cassandra_phase1_core1.trace.xz /data3/CASSANDRA/traces/cassandra_phase1_core2.trace.xz /data3/CASSANDRA/traces/cassandra_phase1_core3.trace.xz > cassandra_phase1_4T_mlop.out 2>&1
/data3/bin/perceptron-multi-multi-no-ship-4core --warmup_instructions=50000000 --simulation_instructions=150000000 --l2c_prefetcher_types=scooby --config=/data3/config/pythia.ini --dram_io_freq=2400 --knob_cloudsuite=true -traces /data3/CASSANDRA/traces/cassandra_phase1_core0.trace.xz /data3/CASSANDRA/traces/cassandra_phase1_core1.trace.xz /data3/CASSANDRA/traces/cassandra_phase1_core2.trace.xz /data3/CASSANDRA/traces/cassandra_phase1_core3.trace.xz > cassandra_phase1_4T_pythia.out 2>&1
/data3/bin/perceptron-multi-multi-no-ship-4core --warmup_instructions=50000000 --simulation_instructions=150000000 --l2c_prefetcher_types=scooby --config=/data3/config/pythia_mod.ini --dram_io_freq=2400 --knob_cloudsuite=true -traces /data3/CASSANDRA/traces/cassandra_phase1_core0.trace.xz /data3/CASSANDRA/traces/cassandra_phase1_core1.trace.xz /data3/CASSANDRA/traces/cassandra_phase1_core2.trace.xz /data3/CASSANDRA/traces/cassandra_phase1_core3.trace.xz > cassandra_phase1_4T_imp_pythia.out 2>&1
/data3/bin/perceptron-multi-multi-no-ship-4core --warmup_instructions=50000000 --simulation_instructions=150000000 --l2c_prefetcher_types=dspatch --config=/data3/config/dspatch.ini --dram_io_freq=2400 --knob_cloudsuite=true -traces /data3/CASSANDRA/traces/cassandra_phase1_core0.trace.xz /data3/CASSANDRA/traces/cassandra_phase1_core1.trace.xz /data3/CASSANDRA/traces/cassandra_phase1_core2.trace.xz /data3/CASSANDRA/traces/cassandra_phase1_core3.trace.xz > cassandra_phase1_4T_dspatch.out 2>&1
/data3/bin/perceptron-multi-multi-no-ship-4core --warmup_instructions=50000000 --simulation_instructions=150000000 --l2c_prefetcher_types=spp_ppf_dev --config=/data3/config/spp_ppf_dev.ini --dram_io_freq=2400 --knob_cloudsuite=true -traces /data3/CASSANDRA/traces/cassandra_phase1_core0.trace.xz /data3/CASSANDRA/traces/cassandra_phase1_core1.trace.xz /data3/CASSANDRA/traces/cassandra_phase1_core2.trace.xz /data3/CASSANDRA/traces/cassandra_phase1_core3.trace.xz > cassandra_phase1_4T_ppf.out 2>&1
/data3/bin/perceptron-multi-multi-no-ship-4core --warmup_instructions=50000000 --simulation_instructions=150000000 --config=/data3/config/nopref.ini --dram_io_freq=2400 --knob_cloudsuite=true -traces /data3/CASSANDRA/traces/cassandra_phase2_core0.trace.xz /data3/CASSANDRA/traces/cassandra_phase2_core1.trace.xz /data3/CASSANDRA/traces/cassandra_phase2_core2.trace.xz /data3/CASSANDRA/traces/cassandra_phase2_core3.trace.xz > cassandra_phase2_4T_nopref.out 2>&1
/data3/bin/perceptron-multi-multi-no-ship-4core --warmup_instructions=50000000 --simulation_instructions=150000000 --l2c_prefetcher_types=spp_dev2 --config=/data3/config/spp_dev2.ini --dram_io_freq=2400 --knob_cloudsuite=true -traces /data3/CASSANDRA/traces/cassandra_phase2_core0.trace.xz /data3/CASSANDRA/traces/cassandra_phase2_core1.trace.xz /data3/CASSANDRA/traces/cassandra_phase2_core2.trace.xz /data3/CASSANDRA/traces/cassandra_phase2_core3.trace.xz > cassandra_phase2_4T_spp.out 2>&1
/data3/bin/perceptron-multi-multi-no-ship-4core --warmup_instructions=50000000 --simulation_instructions=150000000 --l2c_prefetcher_types=bingo --config=/data3/config/bingo.ini --dram_io_freq=2400 --knob_cloudsuite=true -traces /data3/CASSANDRA/traces/cassandra_phase2_core0.trace.xz /data3/CASSANDRA/traces/cassandra_phase2_core1.trace.xz /data3/CASSANDRA/traces/cassandra_phase2_core2.trace.xz /data3/CASSANDRA/traces/cassandra_phase2_core3.trace.xz > cassandra_phase2_4T_bingo.out 2>&1
/data3/bin/perceptron-multi-multi-no-ship-4core --warmup_instructions=50000000 --simulation_instructions=150000000 --l2c_prefetcher_types=mlop --config=/data3/config/mlop.ini --dram_io_freq=2400 --knob_cloudsuite=true -traces /data3/CASSANDRA/traces/cassandra_phase2_core0.trace.xz /data3/CASSANDRA/traces/cassandra_phase2_core1.trace.xz /data3/CASSANDRA/traces/cassandra_phase2_core2.trace.xz /data3/CASSANDRA/traces/cassandra_phase2_core3.trace.xz > cassandra_phase2_4T_mlop.out 2>&1
/data3/bin/perceptron-multi-multi-no-ship-4core --warmup_instructions=50000000 --simulation_instructions=150000000 --l2c_prefetcher_types=scooby --config=/data3/config/pythia.ini --dram_io_freq=2400 --knob_cloudsuite=true -traces /data3/CASSANDRA/traces/cassandra_phase2_core0.trace.xz /data3/CASSANDRA/traces/cassandra_phase2_core1.trace.xz /data3/CASSANDRA/traces/cassandra_phase2_core2.trace.xz /data3/CASSANDRA/traces/cassandra_phase2_core3.trace.xz > cassandra_phase2_4T_pythia.out 2>&1
/data3/bin/perceptron-multi-multi-no-ship-4core --warmup_instructions=50000000 --simulation_instructions=150000000 --l2c_prefetcher_types=scooby --config=/data3/config/pythia_mod.ini --dram_io_freq=2400 --knob_cloudsuite=true -traces /data3/CASSANDRA/traces/cassandra_phase2_core0.trace.xz /data3/CASSANDRA/traces/cassandra_phase2_core1.trace.xz /data3/CASSANDRA/traces/cassandra_phase2_core2.trace.xz /data3/CASSANDRA/traces/cassandra_phase2_core3.trace.xz > cassandra_phase2_4T_imp_pythia.out 2>&1
/data3/bin/perceptron-multi-multi-no-ship-4core --warmup_instructions=50000000 --simulation_instructions=150000000 --l2c_prefetcher_types=dspatch --config=/data3/config/dspatch.ini --dram_io_freq=2400 --knob_cloudsuite=true -traces /data3/CASSANDRA/traces/cassandra_phase2_core0.trace.xz /data3/CASSANDRA/traces/cassandra_phase2_core1.trace.xz /data3/CASSANDRA/traces/cassandra_phase2_core2.trace.xz /data3/CASSANDRA/traces/cassandra_phase2_core3.trace.xz > cassandra_phase2_4T_dspatch.out 2>&1
/data3/bin/perceptron-multi-multi-no-ship-4core --warmup_instructions=50000000 --simulation_instructions=150000000 --l2c_prefetcher_types=spp_ppf_dev --config=/data3/config/spp_ppf_dev.ini --dram_io_freq=2400 --knob_cloudsuite=true -traces /data3/CASSANDRA/traces/cassandra_phase2_core0.trace.xz /data3/CASSANDRA/traces/cassandra_phase2_core1.trace.xz /data3/CASSANDRA/traces/cassandra_phase2_core2.trace.xz /data3/CASSANDRA/traces/cassandra_phase2_core3.trace.xz > cassandra_phase2_4T_ppf.out 2>&1
/data3/bin/perceptron-multi-multi-no-ship-4core --warmup_instructions=50000000 --simulation_instructions=150000000 --config=/data3/config/nopref.ini --dram_io_freq=2400 --knob_cloudsuite=true -traces /data3/CASSANDRA/traces/cassandra_phase3_core0.trace.xz /data3/CASSANDRA/traces/cassandra_phase3_core1.trace.xz /data3/CASSANDRA/traces/cassandra_phase3_core2.trace.xz /data3/CASSANDRA/traces/cassandra_phase3_core3.trace.xz > cassandra_phase3_4T_nopref.out 2>&1
/data3/bin/perceptron-multi-multi-no-ship-4core --warmup_instructions=50000000 --simulation_instructions=150000000 --l2c_prefetcher_types=spp_dev2 --config=/data3/config/spp_dev2.ini --dram_io_freq=2400 --knob_cloudsuite=true -traces /data3/CASSANDRA/traces/cassandra_phase3_core0.trace.xz /data3/CASSANDRA/traces/cassandra_phase3_core1.trace.xz /data3/CASSANDRA/traces/cassandra_phase3_core2.trace.xz /data3/CASSANDRA/traces/cassandra_phase3_core3.trace.xz > cassandra_phase3_4T_spp.out 2>&1
/data3/bin/perceptron-multi-multi-no-ship-4core --warmup_instructions=50000000 --simulation_instructions=150000000 --l2c_prefetcher_types=bingo --config=/data3/config/bingo.ini --dram_io_freq=2400 --knob_cloudsuite=true -traces /data3/CASSANDRA/traces/cassandra_phase3_core0.trace.xz /data3/CASSANDRA/traces/cassandra_phase3_core1.trace.xz /data3/CASSANDRA/traces/cassandra_phase3_core2.trace.xz /data3/CASSANDRA/traces/cassandra_phase3_core3.trace.xz > cassandra_phase3_4T_bingo.out 2>&1
/data3/bin/perceptron-multi-multi-no-ship-4core --warmup_instructions=50000000 --simulation_instructions=150000000 --l2c_prefetcher_types=mlop --config=/data3/config/mlop.ini --dram_io_freq=2400 --knob_cloudsuite=true -traces /data3/CASSANDRA/traces/cassandra_phase3_core0.trace.xz /data3/CASSANDRA/traces/cassandra_phase3_core1.trace.xz /data3/CASSANDRA/traces/cassandra_phase3_core2.trace.xz /data3/CASSANDRA/traces/cassandra_phase3_core3.trace.xz > cassandra_phase3_4T_mlop.out 2>&1
/data3/bin/perceptron-multi-multi-no-ship-4core --warmup_instructions=50000000 --simulation_instructions=150000000 --l2c_prefetcher_types=scooby --config=/data3/config/pythia.ini --dram_io_freq=2400 --knob_cloudsuite=true -traces /data3/CASSANDRA/traces/cassandra_phase3_core0.trace.xz /data3/CASSANDRA/traces/cassandra_phase3_core1.trace.xz /data3/CASSANDRA/traces/cassandra_phase3_core2.trace.xz /data3/CASSANDRA/traces/cassandra_phase3_core3.trace.xz > cassandra_phase3_4T_pythia.out 2>&1
/data3/bin/perceptron-multi-multi-no-ship-4core --warmup_instructions=50000000 --simulation_instructions=150000000 --l2c_prefetcher_types=scooby --config=/data3/config/pythia_mod.ini --dram_io_freq=2400 --knob_cloudsuite=true -traces /data3/CASSANDRA/traces/cassandra_phase3_core0.trace.xz /data3/CASSANDRA/traces/cassandra_phase3_core1.trace.xz /data3/CASSANDRA/traces/cassandra_phase3_core2.trace.xz /data3/CASSANDRA/traces/cassandra_phase3_core3.trace.xz > cassandra_phase3_4T_imp_pythia.out 2>&1
/data3/bin/perceptron-multi-multi-no-ship-4core --warmup_instructions=50000000 --simulation_instructions=150000000 --l2c_prefetcher_types=dspatch --config=/data3/config/dspatch.ini --dram_io_freq=2400 --knob_cloudsuite=true -traces /data3/CASSANDRA/traces/cassandra_phase3_core0.trace.xz /data3/CASSANDRA/traces/cassandra_phase3_core1.trace.xz /data3/CASSANDRA/traces/cassandra_phase3_core2.trace.xz /data3/CASSANDRA/traces/cassandra_phase3_core3.trace.xz > cassandra_phase3_4T_dspatch.out 2>&1
/data3/bin/perceptron-multi-multi-no-ship-4core --warmup_instructions=50000000 --simulation_instructions=150000000 --l2c_prefetcher_types=spp_ppf_dev --config=/data3/config/spp_ppf_dev.ini --dram_io_freq=2400 --knob_cloudsuite=true -traces /data3/CASSANDRA/traces/cassandra_phase3_core0.trace.xz /data3/CASSANDRA/traces/cassandra_phase3_core1.trace.xz /data3/CASSANDRA/traces/cassandra_phase3_core2.trace.xz /data3/CASSANDRA/traces/cassandra_phase3_core3.trace.xz > cassandra_phase3_4T_ppf.out 2>&1
/data3/bin/perceptron-multi-multi-no-ship-4core --warmup_instructions=50000000 --simulation_instructions=150000000 --config=/data3/config/nopref.ini --dram_io_freq=2400 --knob_cloudsuite=true -traces /data3/CASSANDRA/traces/cassandra_phase4_core0.trace.xz /data3/CASSANDRA/traces/cassandra_phase4_core1.trace.xz /data3/CASSANDRA/traces/cassandra_phase4_core2.trace.xz /data3/CASSANDRA/traces/cassandra_phase4_core3.trace.xz > cassandra_phase4_4T_nopref.out 2>&1
/data3/bin/perceptron-multi-multi-no-ship-4core --warmup_instructions=50000000 --simulation_instructions=150000000 --l2c_prefetcher_types=spp_dev2 --config=/data3/config/spp_dev2.ini --dram_io_freq=2400 --knob_cloudsuite=true -traces /data3/CASSANDRA/traces/cassandra_phase4_core0.trace.xz /data3/CASSANDRA/traces/cassandra_phase4_core1.trace.xz /data3/CASSANDRA/traces/cassandra_phase4_core2.trace.xz /data3/CASSANDRA/traces/cassandra_phase4_core3.trace.xz > cassandra_phase4_4T_spp.out 2>&1
/data3/bin/perceptron-multi-multi-no-ship-4core --warmup_instructions=50000000 --simulation_instructions=150000000 --l2c_prefetcher_types=bingo --config=/data3/config/bingo.ini --dram_io_freq=2400 --knob_cloudsuite=true -traces /data3/CASSANDRA/traces/cassandra_phase4_core0.trace.xz /data3/CASSANDRA/traces/cassandra_phase4_core1.trace.xz /data3/CASSANDRA/traces/cassandra_phase4_core2.trace.xz /data3/CASSANDRA/traces/cassandra_phase4_core3.trace.xz > cassandra_phase4_4T_bingo.out 2>&1
/data3/bin/perceptron-multi-multi-no-ship-4core --warmup_instructions=50000000 --simulation_instructions=150000000 --l2c_prefetcher_types=mlop --config=/data3/config/mlop.ini --dram_io_freq=2400 --knob_cloudsuite=true -traces /data3/CASSANDRA/traces/cassandra_phase4_core0.trace.xz /data3/CASSANDRA/traces/cassandra_phase4_core1.trace.xz /data3/CASSANDRA/traces/cassandra_phase4_core2.trace.xz /data3/CASSANDRA/traces/cassandra_phase4_core3.trace.xz > cassandra_phase4_4T_mlop.out 2>&1
/data3/bin/perceptron-multi-multi-no-ship-4core --warmup_instructions=50000000 --simulation_instructions=150000000 --l2c_prefetcher_types=scooby --config=/data3/config/pythia.ini --dram_io_freq=2400 --knob_cloudsuite=true -traces /data3/CASSANDRA/traces/cassandra_phase4_core0.trace.xz /data3/CASSANDRA/traces/cassandra_phase4_core1.trace.xz /data3/CASSANDRA/traces/cassandra_phase4_core2.trace.xz /data3/CASSANDRA/traces/cassandra_phase4_core3.trace.xz > cassandra_phase4_4T_pythia.out 2>&1
/data3/bin/perceptron-multi-multi-no-ship-4core --warmup_instructions=50000000 --simulation_instructions=150000000 --l2c_prefetcher_types=scooby --config=/data3/config/pythia_mod.ini --dram_io_freq=2400 --knob_cloudsuite=true -traces /data3/CASSANDRA/traces/cassandra_phase4_core0.trace.xz /data3/CASSANDRA/traces/cassandra_phase4_core1.trace.xz /data3/CASSANDRA/traces/cassandra_phase4_core2.trace.xz /data3/CASSANDRA/traces/cassandra_phase4_core3.trace.xz > cassandra_phase4_4T_imp_pythia.out 2>&1
/data3/bin/perceptron-multi-multi-no-ship-4core --warmup_instructions=50000000 --simulation_instructions=150000000 --l2c_prefetcher_types=dspatch --config=/data3/config/dspatch.ini --dram_io_freq=2400 --knob_cloudsuite=true -traces /data3/CASSANDRA/traces/cassandra_phase4_core0.trace.xz /data3/CASSANDRA/traces/cassandra_phase4_core1.trace.xz /data3/CASSANDRA/traces/cassandra_phase4_core2.trace.xz /data3/CASSANDRA/traces/cassandra_phase4_core3.trace.xz > cassandra_phase4_4T_dspatch.out 2>&1
/data3/bin/perceptron-multi-multi-no-ship-4core --warmup_instructions=50000000 --simulation_instructions=150000000 --l2c_prefetcher_types=spp_ppf_dev --config=/data3/config/spp_ppf_dev.ini --dram_io_freq=2400 --knob_cloudsuite=true -traces /data3/CASSANDRA/traces/cassandra_phase4_core0.trace.xz /data3/CASSANDRA/traces/cassandra_phase4_core1.trace.xz /data3/CASSANDRA/traces/cassandra_phase4_core2.trace.xz /data3/CASSANDRA/traces/cassandra_phase4_core3.trace.xz > cassandra_phase4_4T_ppf.out 2>&1
/data3/bin/perceptron-multi-multi-no-ship-4core --warmup_instructions=50000000 --simulation_instructions=150000000 --config=/data3/config/nopref.ini --dram_io_freq=2400 --knob_cloudsuite=true -traces /data3/CASSANDRA/traces/cassandra_phase5_core0.trace.xz /data3/CASSANDRA/traces/cassandra_phase5_core1.trace.xz /data3/CASSANDRA/traces/cassandra_phase5_core2.trace.xz /data3/CASSANDRA/traces/cassandra_phase5_core3.trace.xz > cassandra_phase5_4T_nopref.out 2>&1
/data3/bin/perceptron-multi-multi-no-ship-4core --warmup_instructions=50000000 --simulation_instructions=150000000 --l2c_prefetcher_types=spp_dev2 --config=/data3/config/spp_dev2.ini --dram_io_freq=2400 --knob_cloudsuite=true -traces /data3/CASSANDRA/traces/cassandra_phase5_core0.trace.xz /data3/CASSANDRA/traces/cassandra_phase5_core1.trace.xz /data3/CASSANDRA/traces/cassandra_phase5_core2.trace.xz /data3/CASSANDRA/traces/cassandra_phase5_core3.trace.xz > cassandra_phase5_4T_spp.out 2>&1
/data3/bin/perceptron-multi-multi-no-ship-4core --warmup_instructions=50000000 --simulation_instructions=150000000 --l2c_prefetcher_types=bingo --config=/data3/config/bingo.ini --dram_io_freq=2400 --knob_cloudsuite=true -traces /data3/CASSANDRA/traces/cassandra_phase5_core0.trace.xz /data3/CASSANDRA/traces/cassandra_phase5_core1.trace.xz /data3/CASSANDRA/traces/cassandra_phase5_core2.trace.xz /data3/CASSANDRA/traces/cassandra_phase5_core3.trace.xz > cassandra_phase5_4T_bingo.out 2>&1
/data3/bin/perceptron-multi-multi-no-ship-4core --warmup_instructions=50000000 --simulation_instructions=150000000 --l2c_prefetcher_types=mlop --config=/data3/config/mlop.ini --dram_io_freq=2400 --knob_cloudsuite=true -traces /data3/CASSANDRA/traces/cassandra_phase5_core0.trace.xz /data3/CASSANDRA/traces/cassandra_phase5_core1.trace.xz /data3/CASSANDRA/traces/cassandra_phase5_core2.trace.xz /data3/CASSANDRA/traces/cassandra_phase5_core3.trace.xz > cassandra_phase5_4T_mlop.out 2>&1
/data3/bin/perceptron-multi-multi-no-ship-4core --warmup_instructions=50000000 --simulation_instructions=150000000 --l2c_prefetcher_types=scooby --config=/data3/config/pythia.ini --dram_io_freq=2400 --knob_cloudsuite=true -traces /data3/CASSANDRA/traces/cassandra_phase5_core0.trace.xz /data3/CASSANDRA/traces/cassandra_phase5_core1.trace.xz /data3/CASSANDRA/traces/cassandra_phase5_core2.trace.xz /data3/CASSANDRA/traces/cassandra_phase5_core3.trace.xz > cassandra_phase5_4T_pythia.out 2>&1
/data3/bin/perceptron-multi-multi-no-ship-4core --warmup_instructions=50000000 --simulation_instructions=150000000 --l2c_prefetcher_types=scooby --config=/data3/config/pythia_mod.ini --dram_io_freq=2400 --knob_cloudsuite=true -traces /data3/CASSANDRA/traces/cassandra_phase5_core0.trace.xz /data3/CASSANDRA/traces/cassandra_phase5_core1.trace.xz /data3/CASSANDRA/traces/cassandra_phase5_core2.trace.xz /data3/CASSANDRA/traces/cassandra_phase5_core3.trace.xz > cassandra_phase5_4T_imp_pythia.out 2>&1
/data3/bin/perceptron-multi-multi-no-ship-4core --warmup_instructions=50000000 --simulation_instructions=150000000 --l2c_prefetcher_types=dspatch --config=/data3/config/dspatch.ini --dram_io_freq=2400 --knob_cloudsuite=true -traces /data3/CASSANDRA/traces/cassandra_phase5_core0.trace.xz /data3/CASSANDRA/traces/cassandra_phase5_core1.trace.xz /data3/CASSANDRA/traces/cassandra_phase5_core2.trace.xz /data3/CASSANDRA/traces/cassandra_phase5_core3.trace.xz > cassandra_phase5_4T_dspatch.out 2>&1
/data3/bin/perceptron-multi-multi-no-ship-4core --warmup_instructions=50000000 --simulation_instructions=150000000 --l2c_prefetcher_types=spp_ppf_dev --config=/data3/config/spp_ppf_dev.ini --dram_io_freq=2400 --knob_cloudsuite=true -traces /data3/CASSANDRA/traces/cassandra_phase5_core0.trace.xz /data3/CASSANDRA/traces/cassandra_phase5_core1.trace.xz /data3/CASSANDRA/traces/cassandra_phase5_core2.trace.xz /data3/CASSANDRA/traces/cassandra_phase5_core3.trace.xz > cassandra_phase5_4T_ppf.out 2>&1
